language: php

env:
  global:
    secure: "P1XQmn/kCeN0nWypHiwK+5HlRys5LLF3UVdksMjnt3olIiZWmSx4MzPHlKirzcVD0X8DMSEBIphS3cLwLTuEJyCx9XpSsypX9PfRyeZmTRcAnXklkV61k8fvoEEbb18QCtwLIhiGzXVd2JaWAwSod/mmOHU2ns2+ZsKeMb0TOC4="

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - sh acceptance-tests/start-selenium.sh

script:
  - cd acceptance-tests && phpunit && cd -

after_script:
  - sh acceptance-tests/output-screenshots.sh