language: php

env:
  global:
    secure: "KaTSTFEFffNAZB6+JFgYhbyzMgUfKaJ+Ko611yQYLrdtjyrnzgYh5iiL26FStgeBgl7kHtRrOgLgp6aDrWX1vKxObJ+GURntDtYTJoliy6BeaiMpFHGH5jZbtZLYlp8yOgYct5c4cwm2zaBnfbF4x9QxGdXPAnL8qRikQyHl4iM="

php:
  - 5.3
  - 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev
  - mysql -e 'create database drupal;'
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - cd ..
  - drush dl drupal --drupal-project-rename=drupal
  - cd drupal
  - drush site-install --db-url=mysql://root:@127.0.0.1/drupal --yes
  - cp -r ../wconsumer/ ./sites/all/modules/
  - drush en --yes wconsumer
  - cd ../wconsumer/
  - printenv

script:
  - phpunit
  - cd ../drupal/sites/all/modules/wconsumer/integration-tests && phpunit
