language: php

env:
  global:
    secure: "MPZdLy4qYW7KT8VMN+48rBPrx/RLnMkgW84KrJEmK50gKpQS7dXh7sK4G1Q18NQuMVJAboH0yHpm/V68zgswHpmzVeNqDSKNUMHz/bDNN3oDy2HX/seqAzC5DYtcv2c9N6dE+LqZkQLtibcVSOtlYexWOfcKpZy96SzK69v9fNI="

php:
  - 5.3
  - 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev
  - mysql -e 'create database drupal;'
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - cd ..
  - drush dl drupal --drupal-project-rename=drupal
  - cd drupal
  - drush site-install --db-url=mysql://root:@127.0.0.1/drupal --yes
  - mv ../wconsumer ./sites/all/modules/
  - drush en --yes wconsumer
  - cd sites/all/modules/wconsumer/
  - openssl aes-256-cbc -k "$TEST_KEYS_SECRET" -in integration-tests/keys.php.enc -d -a -out integration-tests/keys.php

script:
  - phpunit
  - cd integration-tests && phpunit && cd -
  - php merge-coverage-reports.php