language: php

env:
  global:
    secure: "V04qAStSjKmmSMnx8mqJ2fK77qtSuxvQMxH1B+mNd/55VMVtYiSxCDBbTlECQMTI42miBmuDgVOwzONsF4quSiOc2BK0DXaTU1FYOiMcU1sQ97xEQnj+XvfRqSMTIESXZVX04orSwPzAzIQOwAUoGJuqZKjR5lsWa1MVfP/yFDY="

php:
  - 5.3
  - 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev
  - sh build/scripts/install-drupal.sh
  - sh build/scripts/start-apache.sh
  - sh build/scripts/start-selenium.sh
  - sh build/scripts/decrypt-keys.sh

script:
  - phpunit --configuration .
  - phpunit --configuration integration-tests
  - phpunit --configuration acceptance-tests
  - php merge-coverage-reports.php

after_script:
  - bash build/scripts/upload-screenshots.sh