language: php

env:
  global:
    secure: "NI+jn/g3y646pWAoDb3QmtJChQwanIcIkWIgBRWa6O+ofAdo7AeY2TKeW5rGPhhu2z2hz8QXu7l2ev6SbXvPlFmVUiSzdyEB8T52G1d/W5UYSto02xlysK/7c+08ecVoXaojOyfAfuteBL+PLYdK4aR6Wf8tOqYFFHQ03MfcYlQ="

php:
  - 5.3
  - 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev
  - sh build/scripts/install-drupal.sh
  - sh build/scripts/start-apache.sh
  - sh build/scripts/start-selenium.sh
  - sh build/scripts/decrypt-keys.sh

script:
  - phpunit --configuration .
  - phpunit --configuration integration-tests
  - phpunit --configuration acceptance-tests
  - php merge-coverage-reports.php

after_script:
  - bash build/scripts/upload-screenshots.sh