language: php

env:
  global:
    secure: "P1XQmn/kCeN0nWypHiwK+5HlRys5LLF3UVdksMjnt3olIiZWmSx4MzPHlKirzcVD0X8DMSEBIphS3cLwLTuEJyCx9XpSsypX9PfRyeZmTRcAnXklkV61k8fvoEEbb18QCtwLIhiGzXVd2JaWAwSod/mmOHU2ns2+ZsKeMb0TOC4="

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev
  - sh build/scripts/install-drupal.sh
  - sh build/scripts/decrypt-keys.sh
  - sh build/scritps/start-selenium.sh

script:
  - phpunit --configuration .
  - phpunit --configuration integration-tests
  - phpunit --configuration acceptance-tests
  - php merge-coverage-reports.php

after_script:
  - bash build/scritps/output-screenshots.sh